# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-30 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(default=None, max_length=255, null=True, verbose_name='\u4e2d\u6587\u540d')),
                ('keyword_start_date', models.DateTimeField(default=None, null=True, verbose_name='\u5f00\u59cb\u8ba1\u7b97\u65f6\u95f4')),
                ('keyword_weight', models.FloatField(default=0, verbose_name='\u6743\u91cd')),
            ],
            options={
                'db_table': 'feed_keywords',
                'verbose_name': 'FeedKeywords',
                'verbose_name_plural': 'FeedKeywords',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='\u65e0\u6807\u9898', max_length=255, null=True, verbose_name='\u5a92\u4f53\u540d')),
                ('host_desc', models.CharField(default='\u65e0\u6807\u9898', max_length=255, null=True, verbose_name='\u5a92\u4f53\u63cf\u8ff0')),
                ('host_category', models.CharField(default='\u9ed8\u8ba4', max_length=255, null=True, verbose_name='\u7c7b\u522b')),
                ('host_homepage', models.CharField(default='', max_length=255, null=True, verbose_name='\u4e3b\u9875')),
                ('host_feed_url', models.CharField(default='', max_length=255, null=True, verbose_name='\u4e3b\u9875')),
                ('host_icon', models.CharField(default='', max_length=255, null=True, verbose_name='\u56fe\u6807')),
                ('host_corp_id', models.CharField(default='', max_length=255, null=True, verbose_name='\u8282\u70b9')),
                ('host_info', models.CharField(default='', max_length=255, null=True, verbose_name='\u8282\u70b9')),
            ],
            options={
                'db_table': 'media_entity',
                'verbose_name': 'MediaEntities',
                'verbose_name_plural': 'MediaEntities',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='\u65e0\u6807\u9898', max_length=255, null=True, verbose_name='\u6807\u9898')),
                ('page_url', models.CharField(default='', max_length=255, null=True, verbose_name='url')),
                ('page_content', models.TextField(max_length=10000, verbose_name='\u5185\u5bb9')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindynode_nltk.Host')),
            ],
            options={
                'db_table': 'page_entity',
                'verbose_name': 'PageEntities',
                'verbose_name_plural': 'PageEntities',
            },
        ),
        migrations.AddField(
            model_name='feedkeywords',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindynode_nltk.Page'),
        ),
    ]
