# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0003_keywordsum'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopword_name', models.CharField(default='无标题', max_length=255, null=True, verbose_name='词名')),
                ('stopword_category', models.CharField(default='普通', max_length=255, null=True, verbose_name='类别名')),
                ('stopword_weight', models.FloatField(default=0, verbose_name='权重')),
            ],
            options={
                'verbose_name_plural': 'StopWord',
                'db_table': 'stop_word',
                'verbose_name': 'StopWord',
            },
        ),
    ]
