# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0005_auto_20170731_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedkeywords',
            name='keyword_pos',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='POS'),
        ),
        migrations.AddField(
            model_name='keywordsum',
            name='keyword_pos',
            field=models.CharField(default=None, max_length=255, verbose_name='POS'),
        ),
    ]
