# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0006_auto_20170801_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 1, 14, 50, 36, 469566, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
