# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0008_host_host_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedkeywords',
            old_name='page',
            new_name='keyword_page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='host',
            new_name='page_host',
        ),
    ]
