# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0009_auto_20170802_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsum',
            name='keyword_category',
            field=models.CharField(default='china', max_length=255, null=True, verbose_name='类别'),
        ),
    ]
