# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0013_keywordsum_keyword_time_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NounPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np_name', models.CharField(default=None, max_length=255, null=True, verbose_name='中文名')),
                ('np_json', models.CharField(default=None, max_length=255, null=True, verbose_name='源数组')),
                ('np_source', models.CharField(default=None, max_length=255, null=True, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('np_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindynode_nltk.Page')),
            ],
            options={
                'verbose_name': 'NounPhrase',
                'verbose_name_plural': 'NounPhrase',
                'db_table': 'noun_phrases',
            },
        ),
    ]
