# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0014_nounphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='', max_length=255, null=True, verbose_name='主页面id')),
                ('group_json', models.TextField(max_length=10000, verbose_name='data json')),
                ('group_type', models.CharField(default='today', max_length=255, null=True, verbose_name='时间类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PageGroupEntities',
                'verbose_name': 'PageGroupEntity',
                'db_table': 'page_group_entity',
            },
        ),
    ]
