# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0015_pagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegroup',
            name='group_length',
            field=models.IntegerField(default=1, verbose_name='聚类长度'),
        ),
    ]
