# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0017_pagegroup_group_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_topics',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='tdidf词'),
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='group_category',
            field=models.CharField(default='china', max_length=255, null=True, verbose_name='内容类别'),
        ),
    ]
