# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0018_auto_20170904_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegroup',
            name='group_topics',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='主题词'),
        ),
    ]
