# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0019_pagegroup_group_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='pubDate'),
        ),
    ]
