# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0020_page_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_date',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='pubDate'),
        ),
    ]
