# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0021_auto_20170911_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow_words', models.CharField(default='today', max_length=10000, null=True, verbose_name='关键词数组')),
                ('bow_category', models.CharField(default='today', max_length=255, null=True, verbose_name='类别')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'BOWEntities',
                'verbose_name': 'BOWEntity',
                'db_table': 'bow_entity',
            },
        ),
    ]
