# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0022_bow'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='bow_visible',
            field=models.BooleanField(default=False, verbose_name='已审核'),
        ),
    ]
