# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0023_bow_bow_visible'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX page_entity_fulltext_index ON page_entity(page_title, page_content) WITH PARSER ngram',),
            ('DROP INDEX page_entity_fulltext_index on page_entity',)
        )
    ]
