# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindynode_nltk', '0024_auto_20170924_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_words', models.CharField(default='untitle', max_length=255, null=True, verbose_name='关键词名')),
                ('trend_count', models.IntegerField(default=1, verbose_name='词频')),
                ('trend_category', models.CharField(default='china', max_length=255, null=True, verbose_name='类别')),
                ('trend_visible', models.BooleanField(default=False, verbose_name='已审核')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TrendEntity',
                'verbose_name_plural': 'TrendEntities',
                'db_table': 'trend_entity',
            },
        ),
    ]
